server:
  port: 80 # 운영 환경은 보통 80 포트 사용
  shutdown: graceful

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://prod-db-server:3306/SuWithMe?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  config:
    import: optional:file:.env[.properties]

custom:
  siteMainUri: https://http://www.suwithme.jby9725.site/
logging:
  level:
    root: ERROR # 운영 환경은 에러 수준 로깅