spring:
  application:
    name: SuWithMe
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  type-aliases-package: com.example.demo.vo

custom:
  siteName: SuWithMe